# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7-node-browsers-legacy
        environment:
          DATABASE_URL: "postgres://acart@localhost:5432/acart"

      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: acart
          POSTGRES_DB: acart


    steps:
      - checkout

      - run:
          name: install app dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle


      # Database setup
      - run: bundle exec rake setup
      - run: bundle exec rake test_up

      - run:
          name: Unit tests
          command: |
            bundle exec rake test

      # collect reports
      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots
